### ISSUE TITLE
Adjust the site template based on known content we need to handle.

### ISSUE THREAD

**Issue by mhines-usgs** [usgs-makerspace/wbeep-viz#12]
We need to provide the following

- [ ] the daily map
- [ ] what it is/title/description including the date
- [ ] short blurb about where to learn more about the model data/modeling
- [ ] legend/explanation about the data displayed

**Comment by lindsayplatt** [comment]
Closing because this is now captured in separate issues. See https://github.com/usgs-makerspace/makerspace-sandbox/issues/119 and https://github.com/usgs-makerspace/makerspace-sandbox/issues/116
