### ISSUE TITLE
Display the version of the Vue app and the Tiles in the footer of the Vue app

### ISSUE THREAD

**Issue by mhines-usgs** [usgs-makerspace/wbeep-viz#38]
- [ ] display the version of the Vue app in the footer
- [ ] display the version of the tiles in the footer
- [ ] configure so that it doesn't display on production

Depends on https://github.com/usgs-makerspace/makerspace-sandbox/issues/111 being completed first.

**Comment by abriggs-usgs** [comment]
Going to put this on hold until we get the versioning pattern we will use sorted out.

**Comment by abriggs-usgs** [comment]
Seems that we decided this was not important anymore. If that changes we can reassess the issue. So calling this closed.
