### ISSUE TITLE
Set up a way to version the Vue app

### ISSUE THREAD

**Issue by mhines-usgs** [usgs-makerspace/wbeep-viz#40]
- [ ] check out the interns work to figure out how to do versioning in Vue https://jenkins.wma.usgs.chs.ead/job/Interns_Development/job/nwisweb-tableau-data-connector-build-deploy/configure
- [ ] determine where to push artifacts (artifactory? or gitlab? interns look to be pushing to gitlab?)
- [ ] set up build job to push artifacts to whatever storage

**Comment by lindsayplatt** [comment]
We agreed on a "poor-man's" approach by just using GitHub to version (see https://github.com/usgs-makerspace/makerspace-sandbox/issues/111). To me, that makes this moot. Closing. Please reopen if you feel differently.

@mhines-usgs @abriggs-usgs
