### ISSUE TITLE
Work with Devops/Check s3 bucket settings

### ISSUE THREAD

**Issue by mhines-usgs** [usgs-makerspace/wbeep-viz#7]
Goals
- [x] check tiles at rest on s3 - are they being gzipped?
- [x] inquire about cloudfront settings for s3 buckets - is compression enabled?
- [x] how can we see the logs? can we get these pushed to cloudwatch or somewhere to be reviewed? (wonder if it might help troubleshoot firefox issues?)

**Comment by mhines-usgs** [comment]
created https://internal.cida.usgs.gov/jira/browse/DEVOPS-1107

**Comment by mhines-usgs** [comment]
Shawn enabled cloudfront on both beta and prod
He didn't enable it on test -- is that a problem?

**Comment by abriggs-usgs** [comment]
No problem. That is the weird CHS way of things. There are two internal buckets, 'test' and 'qa,' that don't have cloudfront and two external buckets, 'beta' and 'prod,' that do.

**Comment by lindsayplatt** [comment]
@mhines-usgs can't tell if the question about getting logs was answered in that JIRA ticket or not. Are we good to go on this now?

**Comment by mhines-usgs** [comment]
Nope, I haven't heard anything about logs yet so am waiting on Shawn for that.

**Comment by lindsayplatt** [comment]
Moving to 🚫 - waiting on Shawn.

**Comment by mhines-usgs** [comment]
Shawn is putting in a request to CHS to do the following:
in the prod-owi-logging-bucket there is a cloudfront folder, under that each tier's logs will go under a folder named after the app, so like this for example:
s3://prod-owi-logging-bucket/cloudfront/wbeep-beta/

**Comment by mhines-usgs** [comment]
The logs are actually being added to cloudfront, not to s3, so only the tiers where we have cloudfront set up will we have logs to check out

**Comment by mhines-usgs** [comment]
Logs are enabled on cloudfront now 
https://s3.console.aws.amazon.com/s3/buckets/prod-owi-logging-bucket/cloudfront/?region=us-west-2&tab=overview

They are likely managed by higher level bucket rules as far as aging out the logs goes. If we need more details I can follow up with Shawn. I think this ticket is now done!
