### ISSUE TITLE
Investigate browser support for Vue/Mapbox app

### ISSUE THREAD

**Issue by mhines-usgs** [usgs-makerspace/wbeep-viz#9]
Even though Chrome and Chromium seem to display tiles, I have not had luck with Firefox...
However the examples on Mapbox seem to briefly complain, and then succeed https://docs.mapbox.com/mapbox-gl-js/example/geojson-line/

**Comment by mhines-usgs** [comment]
I'm wondering if it's something else that is causing issues in Firefox, but if we can include this in our Vue app, perhaps we can tell for certain https://docs.mapbox.com/mapbox-gl-js/example/check-for-support/

**Comment by tworr** [comment]
Seems to be working on current versions of Chrome/Firefox/Safari/IE.  I haven't done exhaustive testing on older versions but that should probably come later.

**Comment by lindsayplatt** [comment]
Hmmm I have Firefox 68.0 (64-bit) and don't see any tiles :(

![image](https://user-images.githubusercontent.com/13220910/62374442-97ed0b00-b501-11e9-8002-977d01eef4e1.png)

**Comment by mhines-usgs** [comment]
@lindsayplatt you have to use the public cloudfront URL if you're hitting the beta bucket? otherwise you'll probably be seeing CORS errors in the browser's console

**Comment by tworr** [comment]
The CORS issue seems to be resolved, so this is probably a Firefox problem.  It had been working in Firefox so I'm not sure what changed at this point.

**Comment by abriggs-usgs** [comment]
The newest changes work with Firefox (Linux) locally. So, it could be Windows Firefox related or something with the bucket permissions.

**Comment by tworr** [comment]
This is what was happening before.  Firefox was working fine locally but the tiles wouldn't load from S3.  It was working for awhile but now it seems to be back to the original problem.  I'll have to run a comparison between a local and S3 load and see if there might be a header that the S3 version isn't sending.

**Comment by lindsayplatt** [comment]
Is this blocked by us not having logs (see #7)?

**Comment by tworr** [comment]
Not at this point.  I suspect it's a header issue so I need to look at network activity from a local load vs a  load from S3 and see if there are any differences that would explain the tiles not loading.

**Comment by tworr** [comment]
Issue was resolved by changing Content-Type for tiles from gzip to application/x-protobuf.  Chrome can deal with it incorrectly identified as gzip but Firefox apparently cannot.  tiles and basetiles in beta bucket updated and app now functions correctly in Chrome and Firefox.
